name: SDKs
on: [push]
jobs:
  check-tools:
    runs-on: ubuntu-latest
    steps:
      - run: swift --version
      - run: ls /usr/local/lib/android/sdk/ndk
      - run: find /usr/local/lib/android/sdk/ndk/toolchains
      - run: cat /usr/local/lib/android/sdk/ndk/source.properties
